STATUS_STOPPED = "stopped"
STATUS_STARTING = "starting"
STATUS_RUNNING = "running"
STATUS_ERROR = "error"

PAGE_DASHBOARD = 0
PAGE_PROFILES = 1
PAGE_LOGS = 2
PAGE_SETTINGS = 3

DEFAULT_PROFILE_NAME = "default"
DEFAULT_DNS = "1.1.1.1"
DEFAULT_MODE = "normal"
